package dev.lokspel.practice.util.cooldown;

public enum CooldownObject {

    ENDER_PEARL,
    BRIDGE_ARROW,
    GOLDEN_APPLE,
    FIREWORK_ROCKET,
    FIREBALL_FIGHT_FIREBALL,
    SPECTATOR_VANISH,
    RANDOM_MATCH,
    PLAYER_SETTINGS,
    LEADERBOARD_GUI_REFRESH,
    CUSTOM_KIT_WEIGHTCLASS_CHANGE,
    SERVER_SETUP_MATCH_REFRESH,
    SERVER_SETUP_EVENT_REFRESH,
    SERVER_SETUP_SAVEALLDATA,
    PUBLIC_PARTY_CHANGE,
    BROADCAST_PARTY_CHANGE,

}
